export interface AutocompleteProps {
  options: unknown[];
  renderInput: (params: unknown) => React.ReactNode;
  autoComplete?: boolean;
  autoHighlight?: boolean;
  autoSelect?: boolean;
  blurOnSelect?: 'mouse' | 'touch' | boolean;
  clearIcon?: React.ReactNode;
  clearOnBlur?: boolean;
  clearOnEscape?: boolean;
  clearText?: string;
  closeText?: string;
  defaultValue?: unknown;
  disableClearable?: boolean;
  disableCloseOnSelect?: boolean;
  disabled?: boolean;
  disabledItemsFocusable?: boolean;
  disableListWrap?: boolean;
  disablePortal?: boolean;
  filterOptions?: () => unknown[];
  filterSelectedOptions?: boolean;
  forcePopupIcon?: 'auto' | boolean;
  freeSolo?: boolean;
  fullWidth?: boolean;
  getLimitTagsText?: () => React.ReactNode;
  getOptionDisabled?: () => boolean;
  getOptionKey?: (option: unknown) => string | number;
  getOptionLabel?: (option: unknown) => string;
  groupBy?: (option: unknown) => string;
  handleHomeEndKeys?: boolean;
  id?: string;
  includeInputInList?: boolean;
  inputValue?: string;
  isOptionEqualToValue?: (option: unknown, value: unknown) => boolean;
  limitTags?: number;
  loading?: boolean;
  loadingText?: React.ReactNode;
  multiple?: boolean;
  noOptionsText?: React.ReactNode;
  onChange?: () => void;
  onClose?: () => void;
  onHighlightChange?: () => void;
  onInputChange?: () => void;
  onOpen?: () => void;
  open?: boolean;
  openOnFocus?: boolean;
  openText?: string;
  popupIcon?: React.ReactNode;
  readOnly?: boolean;
  renderGroup?: () => React.ReactNode;
  renderOption?: () => React.ReactNode;
  renderTags?: () => React.ReactNode;
  renderValue?: () => React.ReactNode;
  selectOnFocus?: boolean;
  size?: 'small' | 'medium';
  slotProps?: object;
  sx?: object;
  sx?: React.CSSProperties;
  value?: unknown | unknown[] | null;
}
